name: Publish Staging (105)
run-name: ${{ github.actor }} is Publishing the API to Staging (105) 🚀
on:
  release:
    types: [created]
jobs:
  build_project:
    timeout-minutes: 60
    runs-on:
      labels: self-hosted
    steps:
    - name: Update Deployment
      run: echo "asd"