name: Deploy on VPS

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Deploy edilecek uygulama'
        required: true
        default: 'web'
        type: choice
        options:
          - web
          - ssr
      env:
        description: 'Deploy ortamı'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout kod
        uses: actions/checkout@v3

      - name: deploy.sh için izin ver
        run: chmod +x ./deploy.sh

      - name: deploy.sh çalıştır
        run: ./deploy.sh ${{ github.event.inputs.app }} ${{ github.event.inputs.env }}
