name: Deploy Unirefund Apps

run-name: >
  🚀 ${{ github.actor }} is deploying [${{ inputs.env }}]
  Unirefund-${{ inputs.app }}

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Release type (one of): dev, uat, prod"
        required: true
        default: "uat"
        type: choice
        options:
          - dev
          - uat
          - prod
      app:
        description: "App to publish (web or ssr)"
        required: true
        default: "web"
        type: choice
        options:
          - web
          - ssr

jobs:
  publish:
    runs-on: self-hosted
    timeout-minutes: 60

    # ✅ Activates GitHub Environment for secrets/vars
    environment: ${{ inputs.env }}

    steps:
      - name: Show build context
        run: |
          echo "🎉 Triggered by: ${{ github.actor }}"
          echo "🌍 Environment: ${{ inputs.env }}"
          echo "📦 App: ${{ inputs.app }}"
          echo "🖥️  OS: ${{ runner.os }}"
          echo "🔁 Branch: ${{ github.ref_name }}"

      - name: Validate branch ↔️ environment match
        run: |
          case "${{ inputs.env }}" in
            dev)
              EXPECTED_BRANCH="dev"
              ;;
            uat)
              EXPECTED_BRANCH="uat"
              ;;
            prod)
              EXPECTED_BRANCH="prod"
              ;;
            *)
              echo "❌ Invalid environment selected."
              exit 1
              ;;
          esac

          if [[ "${{ github.ref_name }}" != "$EXPECTED_BRANCH" ]]; then
            echo "❌ You can only deploy '${{ inputs.env }}' from the '$EXPECTED_BRANCH' branch."
            exit 1
          fi

          echo "✅ Branch and environment match."
      - name: Deploy via SSH
        env:
          SSH_COMMAND: |
            deploy Unirefund ${{inputs.app}} ${{inputs.env}}
        run: |
          echo "Running remote deploy command..."
          ssh ubuntu "${SSH_COMMAND}"
