name: Deploy Unirefund Apps
run-name: >
  🚀 ${{ github.actor }} is deploying [${{ github.event.inputs.env }}] ${{ github.event.inputs.app }}

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Release type (one of): uat, dev, prod"
        required: true
        default: "uat"
        type: choice
        options:
          - uat
          - dev
          - prod
      app:
        description: "App to publish (one of): ssr, web"
        required: true
        default: "ssr"
        type: choice
        options:
          - ssr
          - web

jobs:
  publish:
    runs-on: self-hosted
    timeout-minutes: 60
    environment: ${{ github.event.inputs.env }} # Connect to GitHub Environment
    steps:
      - name: Show context
        run: |
          echo "🎉 Triggered by: ${{ github.event_name }}"
          echo "🖥️  Running on: ${{ runner.os }}"
          echo "🌍 Environment: ${{ github.event.inputs.env }}"
          echo "📦 App: ${{ github.event.inputs.app }}"

      - name: Set PORT from environment
        run: |
          if [[ "${{ github.event.inputs.app }}" == "web" ]]; then
          PORT_VALUE="${{ env.WEB_PORT }}"
          elif [[ "${{ github.event.inputs.app }}" == "ssr" ]]; then
          PORT_VALUE="${{ env.SSR_PORT }}"
          else
          echo "❌ Invalid app type: ${{ github.event.inputs.app }}"
          exit 1
          fi

          if [[ -z "$PORT_VALUE" ]]; then
          echo "❌ PORT value is empty! Did you define WEB_PORT/SSR_PORT in the GitHub Environment?"
          exit 1
          fi

          echo "PORT=$PORT_VALUE" >> $GITHUB_ENV

      - name: Run publish script
        run: |
          ssh ubuntu "
            cd ~/frontend/deployment/unirefund/${{ github.event.inputs.env }} &&
            npx -y @deployit/cli@latest deployit \
              --project Unirefund \
              --app ${{ github.event.inputs.app }} \
              --env ${{ github.event.inputs.env }} \
              --sync true \
              --port $PORT"
