name: Enforce Branch PR Flow

on:
  pull_request:
    branches:
      - uat
      - main

jobs:
  validate-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce Branch Flow
        run: |
          BASE="${{ github.event.pull_request.base.ref }}"
          HEAD="${{ github.event.pull_request.head.ref }}"

          echo "🔁 Trying to merge $HEAD into $BASE"

          if [[ "$BASE" == "uat" && "$HEAD" != "dev" ]]; then
            echo "❌ PRs to 'uat' must come from 'dev'"
            exit 1
          fi

          if [[ "$BASE" == "main" && "$HEAD" != "uat" ]]; then
            echo "❌ PRs to 'main' must come from 'uat'"
            exit 1
          fi

          echo "✅ PR source is valid."
