name: Publish apps
run-name: ${{ github.actor }} is publishing projects. 🚀
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Release type (one of): uat,dev"
        required: true
        default: "uat"
        type: choice
        options:
          - uat
          - dev
      app:
        description: "App to publish (one of): ssr, web"
        required: true
        default: "ssr"
        type: choice
        options:
          - ssr
          - web
jobs:
  publish_dev:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Determine port
        id: determine-port
        run: |
          if [[ "${{ github.event.inputs.env }}" == "uat" && "${{ github.event.inputs.app }}" == "web" ]]; then
            echo "PORT=1453" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.env }}" == "dev" && "${{ github.event.inputs.app }}" == "web" ]]; then
            echo "PORT=1454" >> $GITHUB_ENV
          elif [[ "${{ github.event.inputs.env }}" == "uat" && "${{ github.event.inputs.app }}" == "ssr" ]]; then
            echo "PORT=1455" >> $GITHUB_ENV
          else
            echo "Invalid combination of env and app" && exit 1
          fi
      - name: Run a publish script
        run: |
          ssh ubuntu "
            cd ~/frontend/deployment/unirefund/${{ github.event.inputs.env }} &&
            npx -y @deployit/cli@latest deployit \
              --project Unirefund \
              --app ${{ github.event.inputs.app }} \
              --env ${{ github.event.inputs.env }} \
              --sync true \
              --port $PORT"
